-- MySQL Script generated by MySQL Workbench
-- Tue Nov 26 12:45:14 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Country` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Country` (
  `country_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `iso_code` CHAR(2) NOT NULL,
  `prefix` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`country_id`),
  UNIQUE INDEX `iso_code_UNIQUE` (`iso_code` ASC) ,
  UNIQUE INDEX `prefix_UNIQUE` (`prefix` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Clients` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Clients` (
  `user_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `surname` VARCHAR(45) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `dni` VARCHAR(45) NOT NULL,
  `address` VARCHAR(150) NOT NULL,
  `register_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `country_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `country_id`),
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_Clients_Country1_idx` (`country_id` ASC) ,
  CONSTRAINT `fk_Clients_Country1`
    FOREIGN KEY (`country_id`)
    REFERENCES `mydb`.`Country` (`country_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Packs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Packs` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Packs` (
  `pack_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(400) NULL,
  `price` INT UNSIGNED NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 1,
  `duration` INT NOT NULL,
  PRIMARY KEY (`pack_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ReferralSources`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ReferralSources` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ReferralSources` (
  `source_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`source_id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users_book_Packs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Users_book_Packs` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Users_book_Packs` (
  `user_id` INT UNSIGNED NOT NULL,
  `pack_id` INT UNSIGNED NOT NULL,
  `status` ENUM("required", "approved", "completed", "cancelled") NOT NULL DEFAULT 'required',
  `application_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `message` VARCHAR(300) NULL,
  `requested_dates` DATE NOT NULL,
  `source_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`user_id`, `pack_id`),
  INDEX `fk_Users_has_Packs_Packs1_idx` (`pack_id` ASC) ,
  INDEX `fk_Users_has_Packs_Users_idx` (`user_id` ASC) ,
  INDEX `status` (`status` ASC) VISIBLE,
  INDEX `fk_Users_book_Packs_ReferralSources1_idx` (`source_id` ASC) ,
  CONSTRAINT `fk_Users_has_Packs_Users`
    FOREIGN KEY (`user_id`)
    REFERENCES `mydb`.`Clients` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Packs_Packs1`
    FOREIGN KEY (`pack_id`)
    REFERENCES `mydb`.`Packs` (`pack_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_book_Packs_ReferralSources1`
    FOREIGN KEY (`source_id`)
    REFERENCES `mydb`.`ReferralSources` (`source_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Workers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Workers` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Workers` (
  `worker_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `register_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `rol` ENUM("admin", "founder") NOT NULL,
  PRIMARY KEY (`worker_id`),
  INDEX `rol` (`rol` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) )
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
